package io.github.takusan23.newradiosupporter.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006494)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc8e6ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e31)
val md_theme_light_secondary = Color(0xFF006780)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFb3ebff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f29)
val md_theme_light_tertiary = Color(0xFF00629e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFcee5ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001d34)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfcfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdee3ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72787e)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3032)
val md_theme_light_request = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF8bceff)
val md_theme_dark_onPrimary = Color(0xFF003450)
val md_theme_dark_primaryContainer = Color(0xFF004b71)
val md_theme_dark_onPrimaryContainer = Color(0xFFc8e6ff)
val md_theme_dark_secondary = Color(0xFF5cd5fb)
val md_theme_dark_onSecondary = Color(0xFF003543)
val md_theme_dark_secondaryContainer = Color(0xFF004e61)
val md_theme_dark_onSecondaryContainer = Color(0xFFb3ebff)
val md_theme_dark_tertiary = Color(0xFF96cbff)
val md_theme_dark_onTertiary = Color(0xFF003355)
val md_theme_dark_tertiaryContainer = Color(0xFF004a7a)
val md_theme_dark_onTertiaryContainer = Color(0xFFcee5ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e5)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c7ce)
val md_theme_dark_outline = Color(0xFF8b9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e5)
val md_theme_dark_request = Color(0xFF000000)


val seed = Color(0xFF03a9f4)
val error = Color(0xFFba1b1b)